# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/NewwwwwW/ComputerOrg/lab04/Lab04Student/Lab02-IP2SOC-int/A7.xdc

# IP: ip/RAM_B/RAM_B.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet

# IP: ip/Rom_D_0_2/Rom_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rom_D_0 || ORIG_REF_NAME==Rom_D_0} -quiet] -quiet

# XDC: d:/NewwwwwW/ComputerOrg/lab04/Lab04Student/Lab02-IP2SOC-int/Lab02-IP2SOC.gen/sources_1/ip/RAM_B/RAM_B_ooc.xdc

# XDC: d:/NewwwwwW/ComputerOrg/lab04/Lab04Student/Lab02-IP2SOC-int/Lab02-IP2SOC.gen/sources_1/ip/Rom_D_0_2/Rom_D_0_ooc.xdc
