# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/NewwwwwW/ComputerOrg/lab02/Lab02-IP2SOC/Lab02-IP2SOC.srcs/sources_1/ip/Rom_D_0/Rom_D_0.xci
# IP: The module: 'Rom_D_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NewwwwwW/ComputerOrg/lab02/Lab02-IP2SOC/Lab02-IP2SOC.gen/sources_1/ip/Rom_D_0/Rom_D_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rom_D_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/NewwwwwW/ComputerOrg/lab02/Lab02-IP2SOC/Lab02-IP2SOC.srcs/sources_1/ip/Rom_D_0/Rom_D_0.xci
# IP: The module: 'Rom_D_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/NewwwwwW/ComputerOrg/lab02/Lab02-IP2SOC/Lab02-IP2SOC.gen/sources_1/ip/Rom_D_0/Rom_D_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rom_D_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
