# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.runs/synth_1/CSSTE.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.cache/wt} [current_project]
set_property parent.project_path {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{d:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/Seg7_Dev}} [current_project]
update_ip_catalog
set_property ip_output_repo {d:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/coe/P.coe}}
add_files {{D:/ZJU/2.1/Computer Organization/lab/lab4/work/breakDown/TEST/Lab02-IP2SOC-extension/D_mem.coe}}
add_files {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/coe/h.coe}}
read_mem {
  D:/vga_debugger1.mem
  D:/font1_8x16.mem
}
read_verilog -library xil_defaultlib {
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/EX/ALU_more.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/Counter_x.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/Ex_reg_Mem.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/VGA/Hex2Ascii.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/ID_reg_EX.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/IF_reg_ID.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/ID/ImmGen.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/MIO_BUS.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IF/MUX2T1_32.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/WB/MUX4T1_32.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/Mem_reg_WB.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/Multi_8CH32.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/PipelineCPU.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/Pipeline_Ex.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/Pipeline_ID.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/Pipeline_IF.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/Pipeline_Mem.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/Pipeline_WB.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IF/REG32.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/SAnti_jitter.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/ID/SCPU_ctrl.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/SPIO.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/VGA/VGA.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/VGA/VgaController.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/VGA/VgaDebugger.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/VGA/VgaDisplay.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IF/add_32.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/clk_div.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/ID/regs.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/new/stall.v}
  {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/CSSTE.v}
}
read_ip -quiet {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/ip/Seg7_Dev_0/Seg7_Dev_0.xci}}

read_ip -quiet {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/ip/RAM/RAM.xci}}
set_property used_in_implementation false [get_files -all {{d:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.gen/sources_1/ip/RAM/RAM_ooc.xdc}}]

read_ip -quiet {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/sources_1/ip/Rom_D_0_1/Rom_D_0.xci}}
set_property used_in_implementation false [get_files -all {{d:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.gen/sources_1/ip/Rom_D_0_1/Rom_D_0_ooc.xdc}}]

read_edif {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/Counter_x.edf}}
read_edif {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/SAnti_jitter.edf}}
read_edif {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/clk_div.edf}}
read_edif {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/SPIO.edf}}
read_edif {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/Multi_8CH32.edf}}
read_edif {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/MIO_BUS.edf}}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/A7.xdc}}
set_property used_in_implementation false [get_files {{D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/A7.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental {D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.srcs/utils_1/imports/synth_1/CSSTE.dcp}
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top CSSTE -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CSSTE.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CSSTE_utilization_synth.rpt -pb CSSTE_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
