# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/IP/A7.xdc

# IP: ip/Seg7_Dev_0/Seg7_Dev_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Seg7_Dev_0 || ORIG_REF_NAME==Seg7_Dev_0} -quiet] -quiet

# IP: ip/RAM/RAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: ip/Rom_D_0_1/Rom_D_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rom_D_0 || ORIG_REF_NAME==Rom_D_0} -quiet] -quiet

# XDC: d:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.gen/sources_1/ip/RAM/RAM_ooc.xdc

# XDC: d:/ZJU/2.1/Computer Organization/lab/lab5/work/4/finalwork/finalwork.gen/sources_1/ip/Rom_D_0_1/Rom_D_0_ooc.xdc
